source 'http://rubygems.org'

gem 'rake', '0.9.2.2'
gem 'rails', '3.0.9'
gem 'mysql2', '~> 0.2.6'
#gem 'bundler', '1.1.1'
gem 'delayed_job_active_record'
gem 'daemons'

gem 'capistrano', '2.11.2'
gem "haml-rails"
gem 'compass-rails'
gem 'devise', '1.4.2'
gem 'httparty', :git => 'git://github.com/mmangino/httparty.git'
#gem 'facebooker2', '0.0.12', :path => "vendor/gems/facebooker2-0.0.12"
gem 'will_paginate', "~> 3.0.pre2"
gem 'jquery-rails', '>= 1.0.12'
gem "airbrake"
gem "simple-navigation"
gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"
gem 'whenever', :require => false
gem "pusher", "~> 0.8.4"
gem 'aasm'

gem 'omniauth-facebook'
gem 'omniauth'
gem 'oa-core', :require => 'omniauth/core'
gem 'oa-oauth', :require => 'omniauth/oauth'
gem 'mogli', :git => 'git://github.com/alaptev/mogli.git' # forked version '0.0.36'
gem 'fbgraph'
gem 'rack-facebook-method-fix'
gem 'rails_db_dump'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'capybara', '1.1.1' #, :git => 'git://github.com/jnicklas/capybara.git'
  # gem 'capybara-webkit'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'g', "~> 1.4.0"
  gem 'watchr'
  gem 'ar-extensions'
end

group :development do
  gem 'rails-footnotes'
  gem 'rails3-generators'
  gem 'tunnlr_connector', :require => "tunnlr"
end

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'
