source 'https://rubygems.org'

gem 'rails', '3.2.11'

gem 'pg'
gem 'json'

gem 'sass'
gem 'haml'

gem "activeadmin"
gem "formtastic"
gem 'sass-rails'
gem "meta_search", '>= 1.1.0.pre'

gem 'cocaine', '0.3.2'
gem "paperclip", "= 2.7"
gem 'aws-sdk'
gem 'unicode'

gem 'nokogiri'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
