require_relative '../../spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::TournamentsController do
  before(:each) do
    login_admin
  end

  # This should return the minimal set of attributes required to create a valid
  # Tournament. As you add validations to Tournament, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:tournament)
  end

  describe "GET index" do
    it "assigns all tournaments as @tournaments" do
      tournament = Factory(:tournament)
      get :index
      assigns(:tournaments).should eq([tournament])
    end
  end

  describe "GET show" do
    it "assigns the requested tournament as @tournament" do
      tournament = Tournament.create! valid_attributes
      get :show, :id => tournament.id
      assigns(:tournament).should eq(tournament)
    end
  end

  describe "GET new" do
    it "assigns a new tournament as @tournament" do
      get :new
      assigns(:tournament).should be_a_new(Tournament)
    end
  end

  describe "GET edit" do
    it "assigns the requested tournament as @tournament" do
      tournament = Tournament.create! valid_attributes
      get :edit, :id => tournament.id
      assigns(:tournament).should eq(tournament)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tournament" do
        expect {
          post :create, :tournament => valid_attributes
        }.to change(Tournament, :count).by(1)
      end

      it "assigns a newly created tournament as @tournament" do
        post :create, :tournament => valid_attributes
        assigns(:tournament).should be_a(Tournament)
        assigns(:tournament).should be_persisted
      end

      it "redirects to the tournaments index page" do
        post :create, :tournament => valid_attributes
        response.should redirect_to(admin_tournaments_url)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tournament as @tournament" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tournament.any_instance.stub(:save).and_return(false)
        post :create, :tournament => {}
        assigns(:tournament).should be_a_new(Tournament)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tournament.any_instance.stub(:save).and_return(false)
        post :create, :tournament => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tournament" do
        tournament = Tournament.create! valid_attributes
        # Assuming there are no other tournaments in the database, this
        # specifies that the Tournament created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tournament.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tournament.id, :tournament => {'these' => 'params'}
      end

      it "assigns the requested tournament as @tournament" do
        tournament = Tournament.create! valid_attributes
        put :update, :id => tournament.id, :tournament => valid_attributes
        assigns(:tournament).should eq(tournament)
      end

      it "redirects to the tournament" do
        tournament = Tournament.create! valid_attributes
        put :update, :id => tournament.id, :tournament => valid_attributes
        response.should redirect_to(admin_tournament_url(tournament))
      end
    end

    describe "with invalid params" do
      it "assigns the tournament as @tournament" do
        tournament = Tournament.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tournament.any_instance.stub(:save).and_return(false)
        put :update, :id => tournament.id, :tournament => {}
        assigns(:tournament).should eq(tournament)
      end

      it "re-renders the 'edit' template" do
        tournament = Tournament.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tournament.any_instance.stub(:save).and_return(false)
        put :update, :id => tournament.id, :tournament => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tournament" do
      tournament = Tournament.create! valid_attributes
      expect {
        delete :destroy, :id => tournament.id
      }.to change(Tournament, :count).by(-1)
    end

    it "redirects to the tournaments list" do
      tournament = Tournament.create! valid_attributes
      delete :destroy, :id => tournament.id
      response.should redirect_to(admin_tournaments_url)
    end
  end

end
