feeds:
  - http://www.huffingtonpost.com/feeds/index.xml
  - http://feeds.bbci.co.uk/news/rss.xml
  - http://feeds.washingtonpost.com/rss/world
  - http://www.wsj.com/xml/rss/3_7085.xml
  - http://www.theguardian.com/world/rss
  - http://rss.nytimes.com/services/xml/rss/nyt/InternationalHome.xml
  - http://feeds.abcnews.com/abcnews/topstories
  - http://rss.cnn.com/rss/cnn_latest.rss
  - http://feeds.foxnews.com/foxnews/most-popular
  - http://rssfeeds.usatoday.com/usatoday-NewsTopStories
